#!/usr/bin/sh

export PROFILEDIR=debug

make fmt-ci &&
	make build &&
	make build-test-extras &&
	make stratis-dumpmetadata &&
	make build-min &&
	make build-no-ipc &&
	make test &&
	make clippy &&
	make yamllint &&
	make check-typos || exit 1

export PYTHONPATH=$PWD/tests/client-dbus/src

cd tests/client-dbus && make fmt-ci && make lint || exit 1
