#!/bin/bash

if [ $(stratis-min pool is-locked $STRATIS_ROOTFS_UUID) ]; then
	if [ $(stratis-min pool is-bound $STRATIS_ROOTFS_UUID) ]; then
		stratis-min pool unlock clevis $STRATIS_ROOTFS_UUID
	else
		plymouth ask-for-password \
			--command="stratis-min pool unlock --prompt $STRATIS_ROOTFS_UUID" \
			--prompt="Enter root filesystem password" \
			--number-of-tries=3
	fi
fi
