rules:
  default:
    disabling_label: "do not merge"
    protection:
      required_status_checks:
        strict: true
        contexts:
          - continuous-integration/travis-ci
          - stratisd
          - cli-with-stratisd
          - pyup.io/safety-ci
      required_pull_request_reviews:
        required_approving_review_count: 2
