pull_request_rules:
- actions:
    merge:
      method: merge
      rebase_fallback: merge
      strict: true
  conditions:
  - label!=do not merge
  - '#approved-reviews-by>=2'
  - status-success=continuous-integration/travis-ci
  - status-success=stratisd
  - status-success=cli-with-stratisd
  name: default
