rules:
  default:
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        contexts:
        - stratisd
        - pyup.io/safety-ci
        - cli-with-stratisd
        - continuous-integration/travis-ci
