---

# yamllint disable rule:line-length
specfile_path: ../distro/stratisd.spec
merge_pr_in_ci: false
update_release: false

upstream_package_name: stratisd
downstream_package_name: stratisd

actions:
    post-upstream-clone:
        - "git clone https://github.com/stratis-storage/ci --depth=1 ../distro"
        - "bash -c '(cd ../distro; wget https://src.fedoraproject.org/rpms/stratisd/raw/rawhide/f/stratisd.spec)'"
        - "cargo install cargo-get"
        - "cargo install cargo-vendor-filterer"
    create-archive:
        - "sh -c 'python3 ../distro/release_management/create_artifacts.py ../distro/ --pre-release --specfile-path=../distro/stratisd.spec stratisd --vendor-method=filtered'"
    fix-spec-file:
        - "echo 'skipping automatic fix-spec-file actions'"
    get-current-version:
        - "cargo get package.version"

srpm_build_deps:
    - cargo
    - git
    - openssl-devel
    - python3-semantic_version
    - wget2
    - wget2-wget

jobs:
    - job: copr_build
      identifier: copr_pull
      trigger: pull_request
      additional_repos:
          - copr://packit/stratis-storage-libcryptsetup-rs-master
      targets:
          - fedora-all

    - job: copr_build
      identifier: copr_commit
      trigger: commit
      preserve_project: true
      additional_repos:
          - copr://packit/stratis-storage-libcryptsetup-rs-master
      targets:
          - fedora-all

    - job: tests
      identifier: local
      trigger: pull_request
      targets:
          - fedora-all

    # run Cockpit storage tests, see plans/ with `cockpit == yes`
    - job: tests
      identifier: cockpit
      trigger: pull_request
      targets:
          - fedora-development
      notifications:
          failure_comment:
              message: "Cockpit tests failed for commit {commit_sha}. @martinpitt, @jelly, @mvollmer please check."
      tf_extra_params:
          environments:
              - artifacts:
                    - type: repository-file
                      id: https://copr.fedorainfracloud.org/coprs/g/cockpit/main-builds/repo/fedora-$releasever/group_cockpit-main-builds-fedora-$releasever.repo
                tmt:
                    context:
                        plan: "cockpit"

notifications:
    pull_request:
        successful_build: true
