#!/bin/bash

# /run/cryptsetup required for any operation that invokes libcryptsetup or else
# libcryptsetup prints a warning which will be captured in KEY_DESC below the first
# time stratis-min is run.
if [ ! -d /run/cryptsetup ]; then
	mkdir -p /run/cryptsetup
fi

IS_ENCRYPTED=$(stratis-min pool is-encrypted $STRATIS_ROOTFS_UUID)
if [ x"$IS_ENCRYPTED" = x"true" ]; then
	plymouth ask-for-password \
		--command="stratis-min pool setup --pool-uuid=$STRATIS_ROOTFS_UUID" \
		--prompt="Enter root filesystem password" \
		--number-of-tries=3
else
	stratis-min pool setup
fi
