#!/bin/bash

KEY_DESC=$(stratis-min key get-desc $STRATIS_ROOTFS_UUID)

if [ -n "$KEY_DESC" ]; then
	if [ "$(ps -q $$ -o tty --no-headers)" = "?" ]; then
		systemd-ask-password --no-tty | stratis-min key set --no-tty --capture-key $KEY_DESC
	else
		systemd-ask-password | stratis-min key set --capture-key $KEY_DESC
	fi
fi
