#!/bin/bash

# /run/cryptsetup required for any operation that invokes libcryptsetup or else
# libcryptsetup prints a warning which will be captured in KEY_DESC below the first
# time stratis-min is run.
if [ ! -d /run/cryptsetup ]; then
	mkdir -p /run/cryptsetup
fi

if [ -n "$KEY_DESC" ]; then
	plymouth ask-for-password \
		--command="stratis-min pool setup $STRATIS_ROOTFS_UUID" \
		--prompt="Enter root filesystem password"
else
	stratis-min pool setup
fi
