---
name: stratisd release

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  allowed_failures:
    continue-on-error: true
    runs-on: ubuntu-18.04
    container:
      image: fedora:33
    steps:
      - name: Test git status
        run: git log -1
